Fix d.ts types to support import types
momocow/webpack-userscript pull request #37
Opened 2020-08-13 00:53 UTC by vitoyucepi

Redo types with namespace to support member export.

Make types file look like https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webpack-dev-server/index.d.ts
to support code like:
```ts
import WebpackUserscript, {HeaderOptions} from "webpack-userscript";

// currently a cannot import HeaderOptions type
const userscriptHeaders: HeaderOptions = {
    name: 'test'
}

const webpackUserscriptPlugin = new WebpackUserscript({
    headers: userscriptHeaders
});
```

2020-09-03 19:44 UTC, vitoyucepi commented
@momocow any comments?

2020-09-04 02:29 UTC, momocow requested changes

2020-09-04 02:29 UTC, momocow commented on lib/index.d.ts
> +    ssri?: boolean | ssriOptions;
Typo here.

```
Cannot find name 'ssriOptions'.ts(2304)
```

2020-09-04 02:49 UTC, vitoyucepi commented on lib/index.d.ts
> +    ssri?: boolean | ssriOptions;
Fixed. Thank you for review.

2020-09-04 02:53 UTC, momocow approved these changes
Thanks for the contribution.

2020-09-04 02:58 UTC, merged